---

- hosts: all
  vars:
    libevent_version: 2.0.22
    src_dir: /usr/local/src
    libevent_dir: "libevent-{{ libevent_version }}-stable"
    libevent_src_dir: "{{ src_dir }}/{{ libevent_dir }}"
    libevent_src_url: "http://downloads.sourceforge.net/levent/libevent-{{ libevent_version }}-stable.tar.gz"

  tasks:
    - name: remove old yum libevent package
      become: yes
      yum: pkg={{ item }} state=absent
      with_items:
        - libevent
        - libevent-devel
        - libevent-header

    - name: create libevent src dir
      file: path="{{ libevent_src_dir }}" state=directory
      become: yes

    - name: download libevent src
      get_url: url="{{ libevent_src_url }}" dest="{{ src_dir }}"
      become: yes

    - name: extract src file
      command: tar zxvf {{ libevent_dir }}.tar.gz chdir="{{ src_dir }}"
      become: yes

    - name: configure
      command: ./configure chdir="{{ libevent_src_dir }}"
      become: yes

    - name: make
      command: make chdir="{{ libevent_src_dir }}"
      become: yes

    - name: make install
      command: make install chdir="{{ libevent_src_dir }}"
      become: yes

    - name: create synbolic link
      file: src=/usr/local/lib/libevent-2.0.so.5 dest=/usr/lib64/libevent-2.0.so.5 state=link
      become: yes
