---

- hosts: localhost
  vars:
    src_dir: /usr/local/src
    libevent_src_dir: "{{ src_dir }}/libevent"
    libevent_version: 2.0.22
    libevent_src_url: "http://downloads.sourceforge.net/levent/libevent-{{ libevent_version }}-stable.tar.gz"
    libevent_dir: "libevent-{{ libevent_version }}-stable"

  tasks:
    - name: create libevent src dir
      file: path="{{ libevent_src_dir }}" state=directory
      become: yes

    - name: download libevent src
      get_url: url="{{ libevent_src_url }}" dest="{{ libevent_src_dir }}"
      become: yes

    - name: extract src file
      command: tar zxvf libevent-{{ libevent_version }}-stable.tar.gz chdir="{{ libevent_src_dir }}"
      become: yes


    - name: mkdir libevent dir
      file: dest="/usr/local/libevent-{{ libevent_version }}-stable" state=directory
      become: yes

    - name: create synbolic link
      file: src="/usr/local/libevent-{{ libevent_version }}-stable" dest=/usr/local/libevent state=link
      become: yes

    - name: configure
      command: ./configure --prefix=/usr/local/libevent chdir="{{ libevent_src_dir }}/{{ libevent_dir }}"
      become: yes

    - name: make
      command: make chdir="{{ libevent_src_dir }}/{{ libevent_dir }}"
      become: yes

    - name: make install
      command: make install chdir="{{ libevent_src_dir }}/{{ libevent_dir }}" 
      become: yes
