- hosts: devservers
  become: true
  roles:
    - git
    - libevent
    - tmux
    - cpanminus
    - { role: mysql_sandbox, become: false }
    - { role: fish, become: false }
    - { role: dotfiles, become: false }

