---
  - name: install dependency
    become: true
    yum:
      pkg: "{{ item }}"
      state: present
    with_items:
      - zsh
      - vim
      - ctags

  - name: clone dotfiles repo
    git:
      repo: "{{ dotfiles_repo }}"
      dest: "{{ dotfiles_src_dir }}"
      accept_hostkey: yes

  - name: run setup.sh
    shell: sh "{{ dotfiles_src_dir }}/setup.sh"

