---
  - name: Remove old yum libevent package
    yum:
      name: "{{ item }}"
      state: absent
    with_items:
      - libevent
      - libevent-devel
      - libevent-header

  - name: Download libevent and unarchive it
    unarchive:
      src: "{{ libevent_src_url }}"
      dest: "{{ src_dir }}"
      remote_src: yes

  - name: Configure
    command: ./configure
    args:
      chdir: "{{ libevent_src_dir }}"

  - name: Execute make
    make:
      chdir: "{{ libevent_src_dir }}"

  - name: Execute make install
    make:
      chdir: "{{ libevent_src_dir }}"
      target: install

  - name: Create synbolic link
    file:
      src: /usr/local/lib/libevent-2.0.so.5
      dest: /usr/lib64/libevent-2.0.so.5
      state: link
