---
  - name: Install dependency
    yum:
      name: "{{ item }}"
      state: present
    with_items:
      - libselinux-python

  - name: Clone cpanminus repository
    git:
      repo: "{{ cpanminus_repo }}"
      dest: "{{ cpanminus_src_dir }}"
      accept_hostkey: yes
      key_file: "{{ private_key }}"

  - name: Execute make
    command: perl Makefile.PL
    args:
      chdir: "{{ cpanminus_src_dir }}"

  - name: Execute make install
    make:
      chdir: "{{ cpanminus_src_dir }}"
      target: install

  - name: Export cpanminus pathes
    blockinfile:
      path: "{{ bash_profile }}"
      block: |
        # Pathes for cpanminus
        export PERL_CPANM_OPT="--local-lib=$HOME/perl5"
        export PERL5LIB="$HOME/perl5/lib/perl5/i386-linux-thread-multi:$HOME/perl5/lib/perl5"
        export PATH="$HOME/perl5/bin:$PATH"

  - name: Install local lib module
    command: cpanm local::lib
    become: false

