---
  - name: install dependency
    yum:
      pkg: "{{ item }}"
      state: present
    with_items:
      - automake
      - ncurses-devel

  - name: clone tmux repository
    git:
      repo: "{{ tmux_repo }}"
      dest: "{{ tmux_src_dir }}"
      accept_hostkey: yes
      key_file: "{{ private_key }}"

  - name: auto generation
    shell: ./autogen.sh
    args:
      chdir: "{{ tmux_src_dir }}"

  - name: configure
    command: ./configure
    args:
      chdir: "{{ tmux_src_dir }}"

  - name: make
    command: make
    args:
      chdir: "{{ tmux_src_dir }}"

  - name: make install
    command: make install
    args:
      chdir: "{{ tmux_src_dir }}"

