- name: install dependency
  become: yes
  yum: pkg={{ item }} state=present
  with_items:
    - git
    - automake

- name: clone tmux repository
  git: repo="{{ tmux_repo }}" dest="{{ tmux_src_dir }}" accept_hostkey=yes key_file="{{ private_key }}"

- name: auto generation
  command: sh autogen.sh chdir="{{ tmux_src_dir }}"

- name: configure
  command: ./configure chdir="{{ tmux_src_dir }}"

- name: make
  command: make chdir="{{ tmux_src_dir }}"

- name: make install
  command: make install chdir="{{ tmux_src_dir }}"
  become: yes
