---
  - name: Install dependency
    yum:
      name: "{{ item }}"
      state: present
    with_items:
      - automake
      - ncurses-devel

  - name: Clone tmux repository
    git:
      repo: "{{ tmux_repo }}"
      dest: "{{ tmux_src_dir }}"
      accept_hostkey: yes
      key_file: "{{ private_key }}"

  - name: Auto generation
    shell: ./autogen.sh
    args:
      chdir: "{{ tmux_src_dir }}"

  - name: Configure
    command: ./configure
    args:
      chdir: "{{ tmux_src_dir }}"

  - name: Execute make
    make:
      chdir: "{{ tmux_src_dir }}"

  - name: Execute make install
    make:
      chdir: "{{ tmux_src_dir }}"
      target: install
